USE sapana;

CREATE TABLE LEA (
    ID INT PRIMARY KEY,
    NAME VARCHAR(90),
    AGE INT,
    COURSE VARCHAR(88),
    MARKS INT
);

INSERT INTO LEA (ID, NAME, AGE, COURSE, MARKS) 
VALUES 
(1, 'Ram', 24, 'BCA', 87),
(2, 'Hari', 31, 'MBA', 49),
(3, 'Gita', 25, 'DE', 88),
(4, 'Muna', 22, 'BBA', 78);
INSERT INTO LEA (ID, NAME, AGE, COURSE, MARKS)
VALUES (5, 'Sita', 23, 'BCA', 91);
INSERT INTO LEA (ID, NAME, AGE, COURSE, MARKS)
VALUES (6, 'Rita', 26, 'MCA', 82);

SELECT * FROM LEA;

-- How many students are in the table?--

SELECT COUNT (*) AS TOTAL_LEA
FROM LEA;

--How many NAME values are in the table?--
SELECT COUNT(NAME) AS TOTAL_LEA
FROM LEA;

--How many MARK values are in the table?--
SELECT COUNT(MARKS) AS TOTAL_LEA
FROM LEA;

SELECT SUM(MARKS) AS TOTAL_LEA
FROM LEA;

SELECT AVG(MARKS) AS TOTAL_LEA
FROM LEA;

SELECT AVG(AGE) AS AVERAGE_AGE
FROM LEA;

SELECT MIN(MARKS) AS LOWEST_MARKS
FROM LEA;

SELECT MAX(MARKS) AS HIGHEST_MARKS
FROM LEA;

SELECT MIN(AGE) YOUNGEST_AGE
FROM LEA;

SELECT MAX (AGE) AS OLDEST_AGE
FROM LEA;


-- all togetheer--
SELECT
    COUNT(*) AS TOTAL_STUDENTS,
    SUM(MARKS) AS TOTAL_MARKS,
    AVG(MARKS) AS AVERAGE_MARKS,
    MIN(MARKS) AS LOWEST_MARKS,
    MAX(MARKS) AS HIGHEST_MARKS
FROM LEA;

SELECT * FROM LEA;


--GROUP BY -- 
SELECT COURSE , SUM (MARKS) AS TOTAL_LEA
FROM LEA 
GROUP BY COURSE ;


Select course , SUM(MARKS) AS TOTAL_MARKS
from LEA
Group by course;


SELECT COURSE , AVG(MARKS) AS AVERAGE_MARKS
FROM LEA
GROUP BY COURSE;



SELECT COURSE, AVG(MARKS) AS TOTAL_AVG
FROM LEA
GROUP BY COURSE;


SELECT COURSE , COUNT(MARKS) AS STUDENT_MARKS
FROM LEA
GROUP BY COURSE;


SELECT COURSE, COUNT(*) AS STUDENT_COUNT
FROM LEA
GROUP BY COURSE;


-- HAVING--
SELECT COURSE , SUM(MARKS) AS TOTAL_MARKS
FROM LEA
GROUP BY COURSE 
HAVING  SUM(MARKS) > 80 ;

SELECT COURSE , SUM(MARKS) AS TOTAL_ARKS 
FROM LEA
GROUP BY COURSE 
HAVING SUM(MARKS) > 100;

--Find courses that have more than one student.--
SELECT COURSE , COUNT(*) 
FROM LEA
GROUP BY COURSE 
HAVING  COUNT(*) > 1;



SELECT COURSE, AVG(MARKS)
FROM LEA
WHERE MARKS >= 50
GROUP BY COURSE
HAVING AVG(MARKS) > 80;

 --- JOINS -- 

use sapana;

CREATE TABLE DEPARTMENT11 (
    COURSE VARCHAR(88),
    DEPARTMENT_HEAD VARCHAR(90)
);


INSERT INTO DEPARTMENT11 (COURSE,  DEPARTMENT_HEAD)
VALUES
('BCA', 'Mr. Dahal'),
('MBA', 'Ms. Basnet'),
('DE', 'Mr. Gurung'),
('BBA', 'Ms. Rai');

SELECT * FROM DEPARTMENT11;

-- INNER JOINS--


SELECT *
FROM LEA
INNER JOIN DEPARTMENT11
ON LEA.COURSE = DEPARTMENT11.COURSE ;


SELECT 
LEA. NAME,
LEA. COURSE,
DEPARTMENT11 .DEPARTMENT_HEAD
FROM LEA
INNER JOIN DEPARTMENT11
ON LEA.COURSE = DEPARTMENT11.COURSE;

--left join--
select *
from LEA 
left join DEPARTMENT11
on LEA.COURSE = DEPARTMENT11.COURSE;



SELECT 
LEA.NAME,
LEA.COURSE,
DEPARTMENT = DEPARTMENT_HEAD
FROM LEA
LEFT JOIN DEPARTMENT11 
ON LEA.COURSE = DEPARTMENT11.COURSE;



SELECT 
    LEA.NAME,
    LEA.COURSE,
    DEPARTMENT=DEPARTMENT_HEAD
FROM LEA
LEFT JOIN DEPARTMENT11
ON LEA.COURSE = DEPARTMENT11.COURSE;

---right join --
    SELECT
        LEA.NAME,
        LEA.COURSE,
        DEPARTMENT=DEPARTMENT_HEAD
    FROM LEA
    RIGHT JOIN DEPARTMENT11
    ON LEA.COURSE = DEPARTMENT11.COURSE;


    SELECT
    DEPARTMENT11.COURSE,
    DEPARTMENT=DEPARTMENT_HEAD,
    LEA.NAME
FROM LEA
RIGHT JOIN DEPARTMENT11
ON LEA.COURSE = DEPARTMENT11.COURSE;



--full join --
SELECT
    LEA.NAME,
    LEA.COURSE,
    DEPARTMENT=DEPARTMENT_HEAD
FROM LEA
FULL OUTER JOIN DEPARTMENT11
ON LEA.COURSE = DEPARTMENT11.COURSE;


-- shoutcut--

SELECT
    L.NAME,
    L.MARKS,
    D.DEPARTMENT_HEAD
FROM LEA AS L
INNER JOIN DEPARTMENT11 AS D
ON L.COURSE = D.COURSE;