USE sapana;

CREATE TABLE LEA (
    ID INT,
    NAME VARCHAR(90),
    AGE INT,
    COURSE VARCHAR(88),
    MARKS INT
);

INSERT INTO LEA (ID, NAME, AGE, COURSE, MARKS) 
VALUES 
(1, 'Ram', 24, 'BCA', 87),
(2, 'Hari', 31, 'MBA', 49),
(3, 'Gita', 25, 'DE', 88),
(4, 'Muna', 22, 'BBA', 78);

SELECT * FROM LEA;

-- How many students are in the table?--

SELECT COUNT (*) AS TOTAL_LEA
FROM LEA;

--How many NAME values are in the table?--
SELECT COUNT(NAME) AS TOTAL_LEA
FROM LEA;

--How many MARK values are in the table?--
SELECT COUNT(MARKS) AS TOTAL_LEA
FROM LEA;

SELECT SUM(MARKS) AS TOTAL_LEA
FROM LEA;

SELECT AVG(MARKS) AS TOTAL_LEA
FROM LEA;

SELECT AVG(AGE) AS AVERAGE_AGE
FROM LEA;

SELECT MIN(MARKS) AS LOWEST_MARKS
FROM LEA;

SELECT MAX(MARKS) AS HIGHEST_MARKS
FROM LEA;

