use sapana;

--DEFAULT --
CREATE TABLE EMPLOYEE_INFO (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'Active'
);
INSERT INTO EMPLOYEE_INFO (ID, NAME)
VALUES (1, 'Ram');


INSERT INTO EMPLOYEE_INFO (ID, NAME, STATUS)
VALUES (2, 'Hari', 'Inactive');


SELECT * FROM EMPLOYEE_INFO;
--check--

CREATE TABLE EMPLO (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT CHECK (AGE >= 18)
);

INSERT INTO EMPLO
VALUES (1, 'Ram', 24);

INSERT INTO EMPLOYEE_INFO
VALUES (2, 'Hari', 15);


SELECT * FROM EMPLO;    