use sapana;

--DEFAULT --
CREATE TABLE EMPLOYEE_INFO (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'Active'
);
INSERT INTO EMPLOYEE_INFO (ID, NAME)
VALUES (1, 'Ram');


INSERT INTO EMPLOYEE_INFO (ID, NAME, STATUS)
VALUES (2, 'Hari', 'Inactive');


SELECT * FROM EMPLOYEE_INFO;

