use sapana;

--1. GETDATE()--

SELECT GETDATE() AS CURRENT_DATE_TIMgi

--2. CURRENT_TIMESTAMP--


SELECT CURRENT_TIMESTAMP AS CURRENT_DATE_TIME;

--3. YEAR()--

SELECT YEAR('2026-09-15') AS YEAR_VALUE;
--4CAST()--
SELECT
    CAST(GETDATE() AS DATE) AS TODAY;