use sapana;


CREATE TABLE DEPARTMENT (
    COURSE VARCHAR(88),
    DEPARTMENT_HEAD VARCHAR(90)
);
INSERT INTO DEPARTMENT (COURSE, DEPARTMENT_HEAD)
VALUES
('BCA', 'Mr. Dahal'),
('MBA', 'Ms. Basnet'),
('DE', 'Mr. Gurung'),
('BBA', 'Ms. Rai');

SELECT * FROM DEPARTMENT;

