use sapana;


 CREATE TABLE SAPPU (
    EMP_ID INT,
    EMP_NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY INT
);

INSERT INTO SAPPU(EMP_ID, EMP_NAME, DEPARTMENT, SALARY)
VALUES
(1, 'Ram', 'IT', 60000),
(2, 'Hari', 'IT', 75000),
(3, 'Gita', 'HR', 50000),
(4, 'Sita', 'HR', 65000),
(5, 'Muna', 'IT', 75000),
(6, 'Rita', 'Finance', 55000),
(7, 'Kiran', 'Finance', 70000),
(8, 'Farhana','HR',80000);

SELECT * FROM SAPPU;
--LAG MEASN PRIVIOUS --
SELECT 
EMP_NAME,
SALARY,
LAG(SALARY) OVER
(ORDER BY SALARY DESC)
AS PREVIOUS_SALARY
FROM SAPPU;



--lead means next --
SELECT 
EMP_NAME ,
SALARY ,
LEAD(SALARY) OVER (
ORDER BY SALARY DESC) 
AS NEXT_SALARY
FROM SAPPU;


--salary difference from the previous employee:--
SELECT
    EMP_NAME,
    DEPARTMENT,
    SALARY,
    LAG(SALARY) OVER (
        PARTITION BY DEPARTMENT
        ORDER BY SALARY DESC
    ) AS PREVIOUS_SALARY,
    SALARY - LAG(SALARY) OVER (
        PARTITION BY DEPARTMENT
        ORDER BY SALARY DESC
    ) AS SALARY_DIFFERENCE
FROM SAPPU;


SELECT SUM(SALARY)
FROM SAPPU;

SELECT 
EMP_NAME,
DEPARTMENT,
SALARY,
SUM(SALARY) OVER () AS TOTAL_SALARY
FROM SAPPU;


SELECT
    EMP_ID,
    EMP_NAME,
    SALARY,
    SUM(SALARY) OVER (
        ORDER BY EMP_ID
    ) AS RUNNING_TOTAL
FROM SAPPU;