use sapana;
CREATE TABLE EMPLOYEE_PRACTICE (
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY INT,
    BONUS INT
);

INSERT INTO EMPLOYEE_PRACTICE
(EMP_ID, EMP_NAME, DEPARTMENT, SALARY, BONUS)
VALUES
(1, 'Ram', 'IT', 60000, 5000),
(2, 'Hari', 'IT', 75000, NULL),
(3, 'Gita', 'HR', 50000, 3000),
(4, 'Sita', 'HR', 65000, NULL),
(5, 'Muna', 'Finance', 70000, 7000);

SELECT *
FROM EMPLOYEE_PRACTICE;


--ISNULL-- 
SELECT 
EMP_NAME,
BONUS,
ISNULL(BONUS ,0 ) AS BONUS_CLEANED
FROM EMPLOYEE_PRACTICE;

--COALESCE()--
SELECT
    EMP_NAME,
    BONUS,
    COALESCE(BONUS, 0) AS BONUS_CLEANED
FROM EMPLOYEE_PRACTICE;

--NULLIF()--


SELECT
    EMP_NAME,
    SALARY,
    NULLIF(SALARY, 70000) AS RESULT
FROM EMPLOYEE_PRACTICE;



WITH HighSalary AS
(
    SELECT *
    FROM EMPLOYEES
    WHERE SALARY > 70000
)
SELECT *
FROM HighSalary;



---CTE WITH GROUP BY --
WITH DepartmentSalary AS
(
    SELECT
        DEPARTMENT,
        AVG(SALARY) AS AVG_SALARY
    FROM EMPLOYEES
    GROUP BY DEPARTMENT
)
SELECT *
FROM DepartmentSalary;


--Strings function--
--1len--
SELECT
    EMP_NAME,
    LEN(EMP_NAME) AS NAME_LENGTH
FROM EMPLOYEE_PRACTICE;
--2 upper--

SELECT
    EMP_NAME,
    UPPER(EMP_NAME) AS UPPER_NAME
FROM EMPLOYEE_PRACTICE;
--3lower--
SELECT
    EMP_NAME,
    LOWER(EMP_NAME) AS LOWER_NAME
FROM EMPLOYEE_PRACTICE;

--4. LEFT() — take characters from the left
SELECT
    EMP_NAME,
    LEFT(EMP_NAME, 2) AS FIRST_TWO
FROM EMPLOYEE_PRACTICE;

--5. RIGHT() — take characters from the right--
SELECT
    EMP_NAME,
    RIGHT(EMP_NAME, 2) AS LAST_TWO
FROM EMPLOYEE_PRACTICE;

--. SUBSTRING() — extract part of a string--
SELECT
    EMP_NAME,
    SUBSTRING(EMP_NAME, 1, 2) AS PART_OF_NAME
FROM EMPLOYEE_PRACTICE;

--7. TRIM() — remove spaces--
SELECT
    TRIM(EMP_NAME) AS CLEAN_NAME
FROM EMPLOYEE_PRACTICE;
--8. REPLACE() — replace text--

SELECT
    EMP_NAME,
    REPLACE(DEPARTMENT, 'IT', 'Technology') AS NEW_DEPARTMENT
FROM EMPLOYEE_PRACTICE;
---9. CONCAT() — combine strings--
SELECT
    CONCAT(EMP_NAME, ' - ', DEPARTMENT) AS EMPLOYEE_INFO
FROM EMPLOYEE_PRACTICE;



--ALL 
SELECT
    EMP_NAME,
    UPPER(EMP_NAME) AS NAME_UPPER,
    LOWER(DEPARTMENT) AS DEPARTMENT_LOWER,
    LEN(EMP_NAME) AS NAME_LENGTH,
    CONCAT(EMP_NAME, ' works in ', DEPARTMENT) AS EMPLOYEE_DESCRIPTION
FROM EMPLOYEE_PRACTICE;


--view-
SELECT
    EMP_NAME,
    SALARY
FROM EMPLOYEE_PRACTICE
WHERE DEPARTMENT = 'IT';


--practicem-- 
SELECT * 
FROM EMPLOYEE_PRACTICE
WHERE SALARY > 60000;


SELECT
    DEPARTMENT,
    AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEE_PRACTICE
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > 60000;

--What is DISTINCT?--
SELECT DISTINCT DEPARTMENT
FROM EMPLOYEE_PRACTICE;