use sapana;
CREATE TABLE EMPLOYEE_PRACTICE (
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY INT,
    BONUS INT
);

INSERT INTO EMPLOYEE_PRACTICE
(EMP_ID, EMP_NAME, DEPARTMENT, SALARY, BONUS)
VALUES
(1, 'Ram', 'IT', 60000, 5000),
(2, 'Hari', 'IT', 75000, NULL),
(3, 'Gita', 'HR', 50000, 3000),
(4, 'Sita', 'HR', 65000, NULL),
(5, 'Muna', 'Finance', 70000, 7000);

SELECT *
FROM EMPLOYEE_PRACTICE;


--ISNULL-- 
SELECT 
EMP_NAME,
BONUS,
ISNULL(BONUS ,0 ) AS BONUS_CLEANED
FROM EMPLOYEE_PRACTICE;

--COALESCE()--
SELECT
    EMP_NAME,
    BONUS,
    COALESCE(BONUS, 0) AS BONUS_CLEANED
FROM EMPLOYEE_PRACTICE;

--NULLIF()--


SELECT
    EMP_NAME,
    SALARY,
    NULLIF(SALARY, 70000) AS RESULT
FROM EMPLOYEE_PRACTICE;



WITH HighSalary AS
(
    SELECT *
    FROM EMPLOYEES
    WHERE SALARY > 70000
)
SELECT *
FROM HighSalary;



---CTE WITH GROUP BY --
WITH DepartmentSalary AS
(
    SELECT
        DEPARTMENT,
        AVG(SALARY) AS AVG_SALARY
    FROM EMPLOYEES
    GROUP BY DEPARTMENT
)
SELECT *
FROM DepartmentSalary;


--Strings function--
--1len--
SELECT
    EMP_NAME,
    LEN(EMP_NAME) AS NAME_LENGTH
FROM EMPLOYEE_PRACTICE;
--2 upper--

SELECT
    EMP_NAME,
    UPPER(EMP_NAME) AS UPPER_NAME
FROM EMPLOYEE_PRACTICE;
--3lower--
SELECT
    EMP_NAME,
    LOWER(EMP_NAME) AS LOWER_NAME
FROM EMPLOYEE_PRACTICE;

--4. LEFT() — take characters from the left
SELECT
    EMP_NAME,
    LEFT(EMP_NAME, 2) AS FIRST_TWO
FROM EMPLOYEE_PRACTICE;