use sapana;


CREATE TABLE EMP (
    EMP_ID INT,
    EMP_NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY INT
);

INSERT INTO EMP (EMP_ID, EMP_NAME, DEPARTMENT, SALARY)
VALUES
(1, 'Ram', 'IT', 60000),
(2, 'Hari', 'IT', 75000),
(3, 'Gita', 'HR', 50000),
(4, 'Sita', 'HR', 65000),
(5, 'Muna', 'IT', 75000),
(6, 'Rita', 'Finance', 55000),
(7, 'Kiran', 'Finance', 70000),
(8, 'Farhana','HR',80000);


SELECT * FROM EMP;

SELECT 
EMP_NAME,
DEPARTMENT,
SALARY,
ROW_NUMBER () OVER (ORDER BY SALARY DESC) AS ROW_NUM
FROM EMP;

--Rank employees separately within each department?--

SELECT 
EMP_NAME,
DEPARTMENT,
SALARY,

ROW_NUMBER() OVER (
    PARTITION BY DEPARTMENT
    ORDER BY SALARY DESC
) AS ROW_NUM
FROM EMP;

--RANK-
SELECT 
EMP_NAME ,
DEPARTMENT,
SALARY,
RANK()  OVER( ORDER BY SALARY DESC) AS RANK_NUM
FROM EMP;




SELECT
    EMP_NAME,
    DEPARTMENT,
    SALARY,
    RANK() OVER (
        PARTITION BY DEPARTMENT
        ORDER BY SALARY DESC
    ) AS SALARY_RANK
FROM EMP;


SELECT 
EMP_NAME,
DEPARTMENT,
SALARY,
DENSE_RANK() OVER (ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMP;


